apiVersion: 1
datasources:
  - name: ClickHouse
    uid: clickhouse-analytics
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: default
      username: default
    isDefault: true
    editable: true
